# Generated by Django 3.1.8 on 2022-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
